In [41]:
import pandas as pd

# 1. Leer el dataset original
df = pd.read_csv("df_sin_outliers.csv")

# 2. Crear una copia para no alterar el original
df_categorizado = df.copy()

# 3. Reglas de conversión
# QSEXO: 1 -> Masculino, 2 -> Femenino
df_categorizado['QSSEXO'] = df_categorizado['QSSEXO'].map({1: 'Masculino', 2: 'Femenino'})
df_categorizado['QS109'] = df_categorizado['QS109'].map({1: 'Tiene', 2: 'No-tiene'})

# Resto de columnas: 1 -> Sí, 2 -> No
cols_si_no = ['QS208', 'QS102', 'QS500']

for col in cols_si_no:
    df_categorizado[col] = df_categorizado[col].map({1: 'Sí', 2: 'No'})

df_categorizado = df_categorizado.dropna(subset=['QS109'])

# 4. Guardar el nuevo DataFrame en un CSV
df_categorizado.to_csv("df_sin_outliers_categorizado.csv", index=False, encoding='utf-8-sig')

# 5. Mostrar confirmación
print("✅ Archivo 'df_sin_outliers_categorizado.csv' generado con éxito.")
print("Columnas convertidas:", ['QSEXO'] + cols_si_no)

✅ Archivo 'df_sin_outliers_categorizado.csv' generado con éxito.
Columnas convertidas: ['QSEXO', 'QS208', 'QS102', 'QS500']

In [43]:
df_categorizado

,QS23,QSSEXO,QS207C,QS208,QS213C,QS219C,QS900,QS901,QS907,QS102,QS500,QS109
0,38,Femenino,17.0,No,4.315413,6.000000,70.4,152.5,98.9,No,Sí,No-tiene
1,33,Masculino,17.0,Sí,7.000000,2.000000,76.0,158.2,100.4,No,No,No-tiene
2,30,Masculino,21.0,No,5.000000,3.253995,66.0,159.4,87.2,No,No,No-tiene
3,32,Femenino,18.0,Sí,7.000000,2.000000,72.9,157.0,91.7,No,No,No-tiene
4,34,Femenino,26.0,No,3.000000,4.000000,57.3,153.3,80.2,No,No,No-tiene
...,...,...,...,...,...,...,...,...,...,...,...,...
28846,35,Femenino,20.0,Sí,7.000000,3.000000,65.9,152.0,92.9,No,No,No-tiene
28847,15,Masculino,14.0,Sí,2.000000,3.000000,54.5,164.0,69.9,No,No,No-tiene
28848,31,Femenino,20.0,No,3.000000,7.000000,58.4,153.0,84.1,No,No,No-tiene
28849,35,Femenino,18.0,No,4.315413,3.253995,58.4,148.9,90.5,No,No,No-tiene
28850,39,Femenino,25.0,Sí,7.000000,2.000000,65.2,142.2,92.1,No,No,No-tiene

In [42]:
df_categorizado.describe()

,QS23,QS207C,QS213C,QS219C,QS900,QS901,QS907
count,28828.000000,28828.000000,28828.000000,28828.000000,28828.000000,28828.000000,28828.000000
mean,40.451644,19.119039,4.316197,3.253990,69.231204,157.681727,93.391618
std,16.634778,4.839770,2.111380,1.738849,20.384183,10.491502,15.916809
min,15.000000,5.000000,1.000000,1.000000,30.000000,120.000000,55.000000
25%,28.000000,16.000000,3.000000,2.000000,57.900000,150.700000,83.700000
50%,37.000000,18.000000,4.000000,3.253995,66.400000,156.600000,91.700000
75%,51.000000,20.000000,7.000000,3.253995,76.000000,163.300000,99.900000
max,97.000000,68.000000,7.000000,7.000000,200.000000,210.000000,160.000000